repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        types: [python]
        language: system
      - id: ruff-check
        name: ruff check
        stages: [commit]
        entry: poetry run ruff check --fix
        types: [python]
        language: system
      - id: mypy
        name: mypy
        entry: poetry run mypy
        types: [python]
        language: system